function getRouteForCmd(cmd) {
    const map = {
        1: "com_protocol.ClientLoginReq",
        2: "com_protocol.ClientLoginRsp",
        3: "com_protocol.ClientDisconnect",
        11: "com_protocol.ClientLoginReq",
        12: "com_protocol.ClientLoginSingleGameRsp",
        101: "com_protocol.EnterGameReq",
        102: "com_protocol.EnterGameRsp",
        105: "com_protocol.LeaveGameReq",
        106: "com_protocol.LeaveGameRsp",
        112: "com_protocol.KickOutGameToHall",
        113: "com_protocol.KickOutHall",
        115: "com_protocol.ClientGetHallGameInfoReq",
        116: "com_protocol.ClientGetHallGameInfoRsp",
        119: "com_protocol.GetScoreRsp",
        122: "com_protocol.HallRedirectGameLinkReq",
        123: "com_protocol.HallRedirectGameLinkRsp",
        126: "com_protocol.UpdateGameInfoNotify",
        129: "com_protocol.GetRoomStatusListReq",
        130: "com_protocol.GetRoomStatusListRsp",
        131: "com_protocol.HallGetPayIncomeRecordReq",
        132: "com_protocol.HallGetPayIncomeRecordRsp",
        135: "com_protocol.ClientGetBaiRenGoodTrendDataReq",
        136: "com_protocol.ClientGetBaiRenGoodTrendDataRsp",
        207: "com_protocol.DivisionActivityReq",
        208: "com_protocol.DivisionActivityRsp",
        209: "com_protocol.DivisionTeamJoinReq",
        210: "com_protocol.DivisionTeamJoinRsp",
        211: "com_protocol.DivisionPlaceBackReq",
        212: "com_protocol.DivisionPlaceBackRsp",
        214: "com_protocol.DivisionUnreadNotify",
        215: "com_protocol.DivisionSwitchNotify",
        216: "com_protocol.ChangeLoginUrlReq",
        219: "com_protocol.ApiLobbyGameListRsp",
        222: "com_protocol.ApiHallCfgNotify",
        1004: "com_protocol.BroadCastPrizePoolTotalAmount",
        1006: "com_protocol.BroadCastPrizePoolTeamInfo",
        1007: "com_protocol.PrizePoolSwitchNotify",
        1075: "com_protocol.ClientGetGameTrendDataReq",
        1076: "com_protocol.ClientGetGameTrendDataRsp",
        1077: "com_protocol.DivisionActivityListReq",
        1078: "com_protocol.DivisionActivityListRsp",
        1079: "com_protocol.DivisionMineReq",
        1080: "com_protocol.DivisionMineRsp",
        1081: "com_protocol.DivisionRoundListReq",
        1082: "com_protocol.DivisionRoundListRsp",
        10001: "com_protocol.ClientEnterGameReq",
        10002: "com_protocol.ClientEnterGameRsp",
        10003: "com_protocol.ClientEnterGameNotify",
        10009: "com_protocol.ClientLeaveGameNotify",
        10013: "com_protocol.ClientPlayerPrepareReq",
        10014: "com_protocol.ClientPlayerPrepareRsp",
        10015: "com_protocol.ClientPlayerPrepareNotify",
        10016: "com_protocol.ClientReEnterGameReq",
        10017: "com_protocol.ClientReEnterGameRsp",
        10019: "com_protocol.UpdatePlayerStatusNotify",
        10024: "com_protocol.ClientChangeRoomReq",
        10025: "com_protocol.ClientChangeRoomRsp",
        10031: "com_protocol.ClientGetRoomTrendInfoReq",
        10032: "com_protocol.ClientGetRoomTrendInfoRsp",
        10046: "com_protocol.ClientGetUserRecordInfoReq",
        10047: "com_protocol.ClientGetUserRecordInfoRsp",
        10055: "com_protocol.CommonChipsNotify",
        10065: "com_protocol.ClientRewardCroupierReq",
        10066: "com_protocol.ClientRewardCroupierRsp",
        10067: "com_protocol.ClientRewardCroupierNotify",
        10070: "com_protocol.ClientRewardCroupierChangerReq",
        10071: "com_protocol.ClientRewardCroupierChangerRsp",
        10072: "com_protocol.ClientRewardCroupierChangerNotify",
        10073: "com_protocol.MorePlayerRankReq",
        10074: "com_protocol.MorePlayerRankRsp",
        10081: "com_protocol.CommonHashLotterySeedNotify",
        10110: "com_protocol.ClientSingleWalletExceptionNotify",
        11010: "com_protocol.ClientChangeGoldNotify",
        11012: "com_protocol.SwCommonSyncDataNotify",
        11043: "com_protocol.SubtitleBroadcastNotIfyInfo",
        11044: "com_protocol.CommonBattleGameHeatReq", // No route given, placeholder
        11046: "com_protocol.ClientPlayerReserveLeaveReq",
        11047: "com_protocol.ClientPlayerReserveLeaveRsp",
        11214: "com_protocol.ClientNRoundNotOptionTipsNotify",

        // 12011: "com_protocol.FortuneToucanStartReq",
        // 12012: "com_protocol.FortuneToucanStartRsp",
        // 12011: "com_protocol.DragonTreasureStartReq",
        // 12012: "com_protocol.DragonTreasureStartRsp",
        // 12011: "com_protocol.FestivalSaintsStartReq",
        // 12012: "com_protocol.FestivalSaintsStartRsp",
        // 12011: "com_protocol.MahjongWaysStartReq",
        // 12012: "com_protocol.MahjongWaysStartRsp",
        // 12011: "com_protocol.PiratesTreasureStartReq",
        // 12012: "com_protocol.PiratesTreasureStartRsp",
        // 12011: "com_protocol.CrazyStartReq",
        // 12012: "com_protocol.CrazyStartRsp",
        // 12011: "com_protocol.DragonTreasure2StartReq",
        // 12012: "com_protocol.DragonTreasure2StartRsp",
        // 12011: "com_protocol.TreasureBowlStartReq",
        // 12012: "com_protocol.TreasureBowlStartRsp",
        // 12011: "com_protocol.FortuneDragonStartReq",
        // 12012: "com_protocol.FortuneDragonStartRsp",
        // 12011: "com_protocol.AnimalKingDomStartReq",
        // 12012: "com_protocol.AnimalKingDomStartRsp",
        // 12011: "com_protocol.FishingMasterBetInfoReq",
        // 12012: "com_protocol.FishingMasterBetInfoRsp",
        // 12011: "com_protocol.WaterMarginStartReq",
        // 12012: "com_protocol.WaterMarginStartRsp",
        // 12011: "com_protocol.WuKongStartReq",
        // 12012: "com_protocol.WuKongStartRsp",
        // 12011: "com_protocol.MrTurtleStartReq",
        // 12012: "com_protocol.MrTurtleStartRsp",
        // 12011: "com_protocol.DragonVsTigerStartReq",
        // 12012: "com_protocol.DragonVsTigerStartRsp",
        12011: "com_protocol.TreasureMarmosetsStartReq",
        12012: "com_protocol.TreasureMarmosetsStartRsp",
        // 12011: "com_protocol.SambaDanceStartReq",
        // 12012: "com_protocol.SambaDanceStartRsp",
        // 12011: "com_protocol.WorldCupStartReq",
        // 12012: "com_protocol.WorldCupStartRsp",
        // 12011: "com_protocol.SuperFruitStartReq",
        // 12012: "com_protocol.SuperFruitStartRsp",
        // 12011: "com_protocol.WaterMarginStartReq",
        // 12012: "com_protocol.WaterMarginStartRsp",
        // 12011: "com_protocol.SuperAceStartReq",
        // 12012: "com_protocol.SuperAceStartRsp",
        // 12011: "com_protocol.CocosRichesStartReq",
        // 12012: "com_protocol.CocosRichesGetGameScreenRsp",
        // 12011: "com_protocol.FortuneSnakeStartReq",
        // 12012: "com_protocol.FortuneSnakeStartRsp",
        // 12011: "com_protocol.SuperFruitsSlot2StartReq",
        // 12012: "com_protocol.SuperFruitsSlot2StartRsp",
        // 12011: "com_protocol.QueenOfBountyStartReq",
        // 12012: "com_protocol.QueenOfBountyStartRsp",
        // 12011: "com_protocol.WildBountyShowdownStartReq",
        // 12012: "com_protocol.WildBountyShowdownStartRsp",

        12017: "com_protocol.WaterMarginUpdateOptTimeReq",

        12041: "com_protocol.ClientNewUserTipsRsp",
        12101: "com_protocol.CommonElecBetReq",
        12102: "com_protocol.CommonElecBetRsp",
        12551: "com_protocol.ClientPlayerSitDownReq",
        12552: "com_protocol.ClientPlayerSitDownRsp",
        12553: "com_protocol.ClientPlayerSitDownNotify",
        12555: "com_protocol.ClientPlayerChangeSeatReq",
        12556: "com_protocol.ClientPlayerChangeSeatRsp",
        12557: "com_protocol.ClientPlayerChangeSeatNotify"
    };
    return map[cmd] || null;
}

module.exports = {
    getRouteForCmd
};